# Generated by Django 5.1.4 on 2025-01-30 05:19

import api.models.models_validations
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('idU', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(choices=[('admin', 'admin'), ('padre', 'padre'), ('educador', 'educador')], default='padre', max_length=10)),
                ('role_confirmation', models.BooleanField(default=False)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='media/images/usuarios')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('idA', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('edadmin_recomendada', models.PositiveSmallIntegerField()),
                ('edadmax_recomendada', models.PositiveSmallIntegerField()),
                ('num_participantes', models.PositiveIntegerField()),
                ('duracion', models.DurationField()),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Instalacion',
            fields=[
                ('idI', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=50)),
                ('capacidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('idA', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Educador',
            fields=[
                ('idE', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Padre',
            fields=[
                ('idP', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Actividad_programada',
            fields=[
                ('idAP', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('idA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.actividad')),
                ('idE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.educador')),
            ],
        ),
        migrations.AddField(
            model_name='actividad',
            name='idI',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.instalacion'),
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('idR', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=10)),
                ('tipo', models.CharField(max_length=30)),
                ('frecuencia_uso', models.PositiveIntegerField()),
                ('idI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.instalacion')),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.SmallIntegerField()),
                ('fecha', models.DateField()),
                ('comentario', models.CharField(max_length=100, validators=[api.models.models_validations.no_offensive_language])),
                ('idAP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.actividad_programada')),
                ('idU', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('idU', 'idAP'), name='unique_user_activity_combination')],
            },
        ),
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('cod_uni', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_hora', models.DateField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmado', 'Confirmado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=10)),
                ('num_ninos', models.PositiveIntegerField()),
                ('comentarios', models.CharField(max_length=100)),
                ('idAP', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.actividad_programada')),
                ('idP', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.padre')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('idP', 'idAP'), name='unique_reservacion')],
            },
        ),
    ]
