# Generated by Django 5.0.4 on 2024-11-29 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_actividad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('idR', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=10)),
                ('tipo', models.CharField(max_length=30)),
                ('frecuencia_uso', models.PositiveIntegerField()),
                ('idI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.instalacion')),
            ],
        ),
    ]
