# Generated by Django 5.0.4 on 2024-11-29 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_recurso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idU', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Padre',
            fields=[
                ('idP', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.usuario')),
            ],
        ),
    ]
