# Generated by Django 5.0.4 on 2024-11-29 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_usuario_padre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('idA', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Educador',
            fields=[
                ('idE', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.usuario')),
            ],
        ),
    ]
