# Generated by Django 5.0.4 on 2024-11-29 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_administrador_educador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad_programada',
            fields=[
                ('idAP', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('idA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.actividad')),
                ('idE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.educador')),
            ],
        ),
    ]
