# Generated by Django 5.0.4 on 2024-11-29 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_actividad_programada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateField()),
                ('estado', models.CharField(max_length=10)),
                ('num_ninos', models.PositiveIntegerField()),
                ('comentarios', models.CharField(max_length=100)),
                ('idAP', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.actividad_programada')),
                ('idP', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.padre')),
            ],
            options={
                'unique_together': {('idP', 'idAP')},
            },
        ),
    ]
