# Generated by Django 5.0.4 on 2024-11-29 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_reservacion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservacion',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='reservacion',
            constraint=models.UniqueConstraint(fields=('idP', 'idAP'), name='unique_reservacion'),
        ),
    ]
