# Generated by Django 5.0.4 on 2024-12-06 19:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_calificacion_calificacion_unique_calificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservacion',
            name='id',
        ),
        migrations.AddField(
            model_name='reservacion',
            name='cod_uni',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
