# Generated by Django 5.0.4 on 2024-12-09 06:03

import api.models_validations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_reservacion_id_reservacion_cod_uni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='comentario',
            field=models.CharField(max_length=100, validators=[api.models_validations.no_offensive_language]),
        ),
    ]
